//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hai
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_emp
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<System.Guid> parid { get; set; }
        public string parname { get; set; }
        public Nullable<System.Guid> parparid { get; set; }
        public string parparname { get; set; }
        public string idcardno { get; set; }
        public string code { get; set; }
    }
}
