//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hai
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_orders
    {
        public System.Guid oid { get; set; }
        public Nullable<System.Guid> eid { get; set; }
        public Nullable<System.DateTime> odate { get; set; }
        public string todo { get; set; }
        public string ename { get; set; }
        public Nullable<System.Guid> parid { get; set; }
        public string parname { get; set; }
        public Nullable<System.Guid> parparid { get; set; }
        public string parparname { get; set; }
        public Nullable<int> rowcount { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> maxprice { get; set; }
        public Nullable<decimal> minprice { get; set; }
        public Nullable<decimal> coin { get; set; }
        public Nullable<decimal> parcoin { get; set; }
        public Nullable<decimal> parparcoin { get; set; }
        public Nullable<decimal> parrmb { get; set; }
        public Nullable<decimal> parparrmb { get; set; }
    }
}
